### ISSUE TITLE
Add support for shuffle and repeat

### ISSUE THREAD

**Issue by martonborzak** [unfoldedcircle/integration-roon#28]
Roon zones can support shuffle and repeat as well. Add support for these features.

**Comment by zehnm** [comment]
The official Roon npm packages & docs are hard to use, incomplete and sometimes even wrong! Found the shuffle & repeat here:
https://github.com/RoonLabs/node-roon-api-transport/blob/2ee60008a4cdb90c34ff3de58bb4b949067f1d20/lib.js#L317-L336

A better source is the unofficial pyroon Python library:
https://github.com/pavoni/pyroon/blob/981a62b715c0bd31664342a7cff94a8624e18f79/roonapi/roonapi.py#L381C9-L408
